name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache `node_modules`
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install
      # - run: yarn lint

      # - run: yarn test

      - run: yarn  build
