name: Deploy Storybook

on:
  push:
    branches:
      - main
    paths:
      - 'storybook/**'

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Prepare Storybook
        run: |
          yarn build
          yarn build:storybook --quiet

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: storybook-static
