name: DEPLOY DOCS (MANUAL)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache `node_modules`
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install
      - run: yarn build
      #- run: yarn test
      - run: yarn docs

      # - uses: azure/login@v1
      #       with:
      #         creds: ${{ secrets.AZURE_CREDENTIALS }}

      ## TODO write script to deploy to azure storage
