name: PR checks
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Check
        run: |
          yarn dep:check
          yarn build
          yarn lint
          yarn types
          yarn test
