name: PR checks
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache `node_modules`
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Check
        run: |
          yarn manypkg check
          yarn lint
          yarn build
          yarn types
          yarn test
