name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache `node_modules`
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Create "Version Packages" Pull Request --or-- trigger Publish to npm Action
        uses: changesets/action@master
        with:
          publish: yarn pkgs:release
          version: yarn pkgs:version
          title: "Version and Release Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prepare Storybook
        run: |
          yarn build
          yarn build:storybook --quiet

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: storybook-static
